[GLOBAL]
pants_version = "2.10.0"
use_deprecated_python_macros = false
# I need this on my local machine
# ca_certs_path = "./certs.pem"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
]

[python]
interpreter_constraints = [">=3.8"]
macos_big_sur_compatibility = true

[anonymous-telemetry]
enabled = false
